version: 2
jobs:
  build:
    macos:
      xcode: '10.3.0'
    steps:
      - checkout
      - run: yarn
      - run: yarn test
      - run: yarn run dist
      - run: mv dist/*.dmg dist/Kap.dmg
      - store_artifacts:
          path: dist/Kap.dmg
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/ # Force CircleCI to build on tags
